<a href="https://colab.research.google.com/github/Jaewon45/ESAA-practice/blob/main/0314_numpyconcept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. 파이썬 기반의 머신러닝과 생태계 이해

## 01. 머신러닝의 개념
* 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
* 복잡한 조건으로 기존 소프트웨어 코드로 해결하기 어려웠던 많은 문제점들을 해결 가능
* 머신러닝 알고리즘은 데이터를 기반으로 통계적인 신뢰도를 강화하고 에측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 학습하고, 이에 기반한 예측을 수행

### 1. 머신러닝의 분류
* 지도학습 (supervised learning) : 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 테스트분석, NLP, 클러스터링, 차원축소, 강화학습
### 2. 데이터 전쟁
* 머신러닝의 가장 큰 단점은 데이터에 매우 의존적이라는 점. 좋은 품질의 데이터를 갖추어야 머신러닝의 수행결과가 좋을 수 있음 
### 3. 파이썬과 R 기반의 머신러닝 비교
* R : 통계 전용 프로그램 언어, 다양하고 많은 통계 패키지 보유
* 파이썬 : 다양한 영역에서 사용되는 개발 전문 프로그램 언어. 직관적 문법과 객체지향과 함수형 프로그래밍을 포괄하는 프로그램 아키텍처, 다양한 라이브러리 등의 강점을 가짐

## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지
* 머신러닝 패키지 : 사이킷런 (scikit learn)
* 행렬/선형대수/통계 패키지 : 넘파이(numpy)
* 데이터 핸들링 : 판다스 (pandas)
* 시각화 : 맷플롯립, 시본 (seaborn)
* 주피터 노트북 (jupyter notebook) : 아이파이썬 지원 툴



## 03. 넘파이
##### 머신러닝의 주요 알고리즘이 바탕으로 하는 선형대수 기반 프로그램을 만들 수 있도록 지원하는 파이썬 패키지. 빠른 배열 연산 속도를 보장하며 저수준 언어 기반의 호환 API (C/C++)를 제공함. 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있음

### 1. 넘파이 ndarray 개요
* ndarray : 넘파이의 기반 데이터 타입, 다차원배열을 쉽게 생성 가능

* array() 함수 : 다양한 인자를 입력받아 ndarray로 변환, shape 변수를 통해 행과 열의 수 (차원)를 튜플 형태로 알 수 있음

In [2]:
import numpy as np

array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


### 2. ndarray의 데이터 타입
* 숫자 값, 문자열 값, 불 값이 가능하며, 연산 특성상 같은 데이터 타입만 가능함
* 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경시 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함
 * int형 + string형은 문자열 값, int형 + float형은 float형으로 변한됨

* astype() 안에 인자로 원하는 타입을 문자열로 지정하면 ndarray 내 데이터값의 타입 변경 가능


In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [9]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)



['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [10]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### 3. ndarray를 편리하게 생성하기 - arange, zeros, ones
* 특정 크기, 차원의 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성 가능

In [12]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [13]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4. ndarray의 차원과 크기를 변경하는 reshape()
* reshape()는 ndarray를 특정 차원 및 크기로 변환, 변환을 원하는 크기를 함수 인자로 부여 가능함. 만약 지정된 사이즈로 변경이 불가능하면 오류 발생
* 인자로 -1를 적용하는 경우 ndarray와 호환되는 새로운 shape로 변환해줌

In [20]:
array1 = np.arange(10) 
print('array1:\n', array1) 

array2 = array1.reshape(2, 5) 
print('array2:\n', array2) 

array3 = array1 .reshape(5, 2) 
print( 'array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
array1 = np.arange(10) 
print(array1) 
array2 = array1.reshape(-1, 5) 
print('array2 shape:', array2.shape) 
array3 = array1.reshape(5, -1) 
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [23]:
# 오류 발생
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [22]:
array1= np.arange(8) 
array3d= array1.reshape((2, 2, 2)) 
print('array3d:\n', array3d.tolist()) 

#3차원 ndarray를 2차원 ndarray로 변환 
array5 = array3d. reshape(-1, 1) 
print('array5:\n', array5. tolist()) 
print('array5 shape:', array5. shape) 

#1차원 ndarray를 2차원 ndarray로 변환 
array6 = array1 .reshape(-1, 1) 
print('array6:\n', array6.tolist()) 
print('array6 shape:', array6 .shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 5. 넘파이의 ndarray의 데이터세트 선택하기 - 인덱싱(indexing)

* 1. 특정한 데이터만 추출 : 원하는 위치의 인덱스값 지정하면 해당 위치의 데이터 반환


In [25]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

# 단일 인덱스를 이용한 ndarray 내의 데이터값 수정
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]


In [26]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:',array2d[0,0])
print('(row=0,col=1) index 가리키는 값:',array2d[0,1])
print('(row=1,col=0) index 가리키는 값:',array2d[1,0])
print('(row=2,col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* 2. 슬라이싱 (slicing) : 연속된 인덱스상의 ndarray 추출. ':' 기호 사이에 시작인덱스와 종료인덱스를 표시하면 시작인덱스에서 종료인덱스-1 위치에 있는 데이터의 ndarray 반환
  * 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원ndarray를 반환 

In [28]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

#슬라이싱 기호 ':' 사이의 시작, 종료 인덱스 생략 가능
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2] \n',array2d[0:2,0:2])
print('array2d[1:3,0:3] \n',array2d[1:3,0:3])
print('array2d[1:3,:] \n',array2d[1:3,:])
print('array2d[:,:] \n',array2d[:,:])
print('array2d[:2,1:] \n',array2d[:2,1:])
print('array2d[:2,0] \n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


In [30]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* 3. 팬시 인덱싱(fancy indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환


In [31]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] -> ',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] -> ',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] -> ',array5.tolist())

array2d[[0,1],2] ->  [3, 6]
array2d[[0,1],0:2] ->  [[1, 2], [4, 5]]
array2d[[0,1]] ->  [[1, 2, 3], [4, 5, 6]]


* 4. 불린 인덱싱(boolean indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환, 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환함


In [32]:
array1d=np.arange(start=1,stop=10)
#[]안에 array1d>5 Voolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)
array1d>5

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [33]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [34]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


### 6. 행렬의 정렬 - sort()와 argsort()
* 행렬 정렬
 * np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
 * ndarray.sort() : 행렬 자체를 정렬한 형태로 변환하며 반환값은 None

In [38]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [40]:
#내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [41]:
array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 정렬된 행렬의 인덱스 반환
 * np.argsort() : 정렬 향렬의 원본 행렬 인덱스를 ndarray 형으로 반환. 넘파이에서 매우 활용도가 높음. 넘파이의 ndarray는 메타 데이터를 가질 수 없기 때문

In [42]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [44]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [45]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']



### 7. 선형대수 연산 - 행렬 내적과 전치행렬 구하기
* 행렬 내적 (행렬 곱)


In [46]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [48]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
