<a href="https://colab.research.google.com/github/Jaewon45/ESAA-practice/blob/main/0314_NumpyExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
nullvector = np.zeros(10)
print(nullvector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [146]:
print("Memory size of a array: ", nullvector.size * nullvector.itemsize, "byte")

Memory size of a array:  80 byte


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [147]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array0 = np.zeros(10)
array0 [4] = 1
print ( array0 )


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
org_vector = np.arange(10,50)
np.sort(org_vector)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1 = (np.arange(0,9))
matrix1 = array1.reshape(3, 3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array2 = np.array([1,2,0,0,4,0])
print(array2[array2 != 0])

[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
matrix2 = np.eye(3, 3)
print(matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
array3 = np.random.rand(3, 3, 3)
print(array3)

[[[0.7795996  0.18509547 0.90392912]
  [0.10735695 0.85307441 0.37321636]
  [0.54117872 0.72592012 0.27862001]]

 [[0.59007627 0.15462501 0.00710609]
  [0.3231783  0.59992173 0.59364548]
  [0.32703748 0.5065807  0.94596236]]

 [[0.41905171 0.11489932 0.29386991]
  [0.86605307 0.40477925 0.82529496]
  [0.66972983 0.79293812 0.91619201]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array4 = np.random.rand(10, 10)
print(array4)
print ('maximum is:', np.max(array4))
print ('minimum is:', np.min(array4))

[[0.46450003 0.85630311 0.95092596 0.91800732 0.84659043 0.33148575
  0.73715564 0.63964242 0.83418731 0.9152857 ]
 [0.78842945 0.70243729 0.3597374  0.83420745 0.32189692 0.8836097
  0.53717904 0.63979519 0.63407134 0.559217  ]
 [0.50501692 0.12791086 0.02800476 0.45265692 0.18607432 0.05087411
  0.14097129 0.10028935 0.85897739 0.48684613]
 [0.49686889 0.90078562 0.65247474 0.69274767 0.89723217 0.00228941
  0.84212588 0.97331427 0.24123105 0.51537274]
 [0.0200394  0.32382081 0.91245063 0.51733101 0.61817198 0.00374709
  0.48278877 0.70543781 0.21050772 0.1482378 ]
 [0.8180959  0.94971998 0.14735576 0.47595668 0.51513323 0.92499762
  0.56872806 0.51461123 0.47018419 0.46452697]
 [0.26793191 0.89224801 0.92697134 0.97533091 0.46713786 0.27178426
  0.45461133 0.11838351 0.76242976 0.18637372]
 [0.86488233 0.39800541 0.78852428 0.11347713 0.19678562 0.72023198
  0.34653619 0.7188134  0.28919857 0.07026998]
 [0.59259426 0.06470787 0.55446561 0.22468711 0.28452696 0.49690188
  0.29121684 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
array5 = np.random.rand(30)
np.mean(array5)

0.4486220615162169

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array6 = np.ones((4,4))
array6[1:-1,1:-1] = 0
print(array6)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
array7 = np.random.rand (3, 3)
array8 = np.pad(array7, pad_width=1, mode='constant',
               constant_values=0)
print(array8)

[[0.         0.         0.         0.         0.        ]
 [0.         0.39349693 0.56321679 0.8766441  0.        ]
 [0.         0.87284682 0.96320921 0.530296   0.        ]
 [0.         0.25351259 0.93224284 0.41361938 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [148]:
# nan, False, False, nan, True, False

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
x = np.diag(np.arange(1, 5), k=-1) # k<0: 주 대각선 아래의 대각선에 대입 
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x = np.zeros((8, 8))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
array10=np.zeros(64)
array10=array10.reshape(8,8)

for i in range(0,8):
  for j in range(0,8):
    if (i+j)%2 == 1:
      array10[i,j]=1
  
print(array10)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile(([[0, 1], [1, 0]]),(4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
array_org = np.random.rand(5, 5)
eigenvalue, eigenvector = np.linalg.eig(array_org)
print(eigenvector)

[[ 0.49600366+0.j          0.66571764+0.j         -0.28624673+0.j
  -0.22252227+0.15816008j -0.22252227-0.15816008j]
 [ 0.55653556+0.j         -0.49861911+0.j          0.49886722+0.j
  -0.58205849+0.j         -0.58205849-0.j        ]
 [ 0.4296653 +0.j         -0.45166364+0.j          0.58795364+0.j
   0.46050197+0.04177869j  0.46050197-0.04177869j]
 [ 0.25466263+0.j          0.26357036+0.j         -0.46412445+0.j
  -0.24300298+0.32294181j -0.24300298-0.32294181j]
 [ 0.44134253+0.j          0.18635888+0.j         -0.32877547+0.j
   0.26464537-0.3734844j   0.26464537+0.3734844j ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [150]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
np.random.rand(5, 3) @ np.random.rand(3, 2)

array([[0.36913567, 0.26972694],
       [0.44068792, 0.53635905],
       [0.86000364, 0.48609982],
       [0.87366533, 0.48887557],
       [0.55946642, 0.35001051]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
x = np.arange(10)
x[(x > 3) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [152]:
# 9, 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.random.randint(5)
# Z**Z, 2 << Z >> 2, 1j*Z, Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan, 0, 0에 가까운 float

#### 29. How to round away from zero a float array ? (★☆☆)

In [155]:
array11 = np.random.uniform(-10,+10,10)
print(array11)
print(np.copysign(np.ceil(np.abs(array11)), array11))

[-4.99820061 -1.32617047  4.77973458  9.13822079  4.11715984 -9.19705787
 -0.06095112  9.37143883  5.91227774 -2.767894  ]
[ -5.  -2.   5.  10.   5. -10.  -1.  10.   6.  -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [156]:
array12 = np.random.randint(0,10,10)
array13 = np.random.randint(0,10,10)
print(array12)
print(array13)
print(np.intersect1d(array12,array13))

[4 4 2 5 1 9 0 5 9 9]
[8 5 5 1 2 5 4 9 8 2]
[1 2 4 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [159]:
with np.errstate(all="ignore"):
    np.arange(5) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [164]:
np.sqrt(-1) == np.emath.sqrt(-1)
#False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [166]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2022-03-13
2022-03-14
2022-03-15
