<a href="https://colab.research.google.com/github/Jaewon45/ESAA-practice/blob/main/0318_numpypractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
np.arange( '2016-07', '2016-08', dtype = 'datetime64[D]') # 시작날짜와 종료날짜, [M], [D]로 날짜 단위 지정

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.ones(2)*1
B=np.ones(2)*2
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
array36 = np.random.normal(10, 5, 5)
print(array36)
print(np.ceil(array36)-1)
print(np.floor(array36))
print(array36.astype(int))
print(array36 - array36%1)

[18.77234765  6.67538266  7.06462377 18.40155772 14.68916523]
[18.  6.  7. 18. 14.]
[18.  6.  7. 18. 14.]
[18  6  7 18 14]
[18.  6.  7. 18. 14.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.random.randint(0, 4, size=(5,5))

array([[0, 3, 0, 2, 3],
       [0, 1, 1, 0, 2],
       [1, 1, 2, 0, 0],
       [0, 2, 1, 1, 3],
       [3, 0, 2, 1, 0]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
  temp=[]
  for i in range(10):
   temp.append(np.random.randint(10, dtype=int))
  np.asarray(temp)
  return(temp)

generator()

[4, 5, 6, 7, 1, 5, 0, 6, 3, 5]

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
org40 = np.random.rand(10)
org40.sort()
print(org40)

[0.04884342 0.06081435 0.0663449  0.12907842 0.22239546 0.26733566
 0.40104742 0.49814682 0.5905419  0.92506352]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
%%time
array41=np.arange(10)
for i in range(1000):
  np.sum(array41)

CPU times: user 6.45 ms, sys: 12 µs, total: 6.47 ms
Wall time: 6.4 ms


In [ ]:
%%time
array41=np.arange(10)
for i in range(1000):
  np.add.reduce(array41) # reduce : 결과가 하나 남을때까지 해당 연산 반복

CPU times: user 3.51 ms, sys: 0 ns, total: 3.51 ms
Wall time: 3.54 ms


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(10, size=5)
B = np.random.randint(10, size=5)
print(A)
print(B)

#nonequal

[3 4 7 8 8]
[2 9 4 1 0]


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
array43 = np.random.randint(10, size=10)
array43.flags.writeable=False
array43[0]=5

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
matrix44 = np.random.random((10,2))
print(matrix44)

[[0.71228006 0.24209519]
 [0.50949881 0.22666892]
 [0.21945476 0.62010476]
 [0.2708567  0.86112107]
 [0.65056518 0.70665811]
 [0.79678925 0.34810566]
 [0.78449296 0.25825911]
 [0.1982207  0.2324248 ]
 [0.81282442 0.90660349]
 [0.65199581 0.4450627 ]]


In [ ]:
X, Y = matrix44[:,0], matrix44[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X) # arctan는 출력 범위가 [-pi/2, pi/2], arctan2는 출력 범위가 [-pi, pi]
print(R)
print(T)

[0.75229846 0.5576449  0.65779199 0.90271416 0.96052107 0.86951174
 0.82590978 0.30547133 1.21762614 0.78941709]
[0.32763779 0.41859304 1.2306518  1.26605438 0.82670384 0.41189454
 0.31803059 0.86465698 0.83988504 0.59896325]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
array45 = np.random.random(10)
print(array45)
array45[array45.argmax()]=0
print(array45)

[0.00515589 0.40278051 0.66857877 0.64925398 0.89352511 0.12993776
 0.71911398 0.70707134 0.31154625 0.30570449]
[0.00515589 0.40278051 0.66857877 0.64925398 0.         0.12993776
 0.71911398 0.70707134 0.31154625 0.30570449]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
np.ones ((3,3), [('x', float), ('y', float)])

array([[(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)],
       [(1., 1.), (1., 1.), (1., 1.)]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(6)
Y = np.arange(6) + 0.5
C = 1. / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for stype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(stype).min)
  print(np.iinfo(stype).max)

for stype in [np.float32, np.float64]:
  print(np.finfo(stype).min)
  print(np.finfo(stype).max) # epsilon

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
given_scalar = np.random.normal(10, 2, 1)
print(given_scalar)
value_set = np.arange(15)
index = np.abs(value_set - given_scalar).argmin()
print(value_set[index])

[10.31054689]
10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
position = ('position', [('x', float), ('y', float)])
color = ('color', [('r', float), ('g', float), ('b', float)])
np.zeros(5, [position, color])

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vector52 = np.random.random((100, 2))
X, Y = np.atleast_2d(vector52[:, 0], vector52[:, 1]) # 입력값을 2차원 이상 배열로 봄
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.34190066 0.5975028  ... 0.38628731 0.52912194 0.16733534]
 [0.34190066 0.         0.76782644 ... 0.53432063 0.44233453 0.26191599]
 [0.5975028  0.76782644 0.         ... 0.23472552 0.48217111 0.52898423]
 ...
 [0.38628731 0.53432063 0.23472552 ... 0.         0.32716862 0.29573733]
 [0.52912194 0.44233453 0.48217111 ... 0.32716862 0.         0.36418021]
 [0.16733534 0.26191599 0.52898423 ... 0.29573733 0.36418021 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
array53 = np.arange(5, dtype=np.float32)
array53.astype(np.int32)

array([0, 1, 2, 3, 4], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [32]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
read = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(read)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
array55 = np.arange(10).reshape(2, 5)
for index, value in np.ndenumerate(array55):
  print (index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [29]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
array57 = np.zeros((5,5))
np.put(array57, np.random.choice(range(5*5), 3),1)
print(array57)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix58 = np.random.rand(4,5)
for i in range(4):
  print(np.mean(matrix58[i,]))

0.2998674991722746
0.6540200077080216
0.7261448445286898
0.23825586661301115


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
array59 = np.random.rand(5, 5)
print(array59[array59[:,3].sort()]) # 4th column

[[[0.2779949  0.72242474 0.08373325 0.21586037 0.2089857 ]
  [0.41552489 0.18203838 0.05013861 0.24604651 0.77081008]
  [0.78192053 0.03523337 0.24659795 0.39257923 0.78133884]
  [0.44967146 0.63708724 0.22146563 0.64175499 0.91496959]
  [0.86585458 0.49761056 0.23742204 0.66823147 0.29342479]]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
array60 = np.random.randint(0,10,(2,5))
print((~array60.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
given_value = np.random.normal(10, 2, 1)
print(given_value)
array61 = np.arange(15)
index = np.abs(array61 - given_value).argmin()
print(value_set[index])

[7.66559532]
8


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [28]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

it = np.nditer([A,B, None])

for x,y,z in it:
    z[...] = x + y
    
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [27]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

A = NamedArray(np.arange(5), "name")
print(A.name)

name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [25]:
vector1 = np.ones(10, dtype=int)
vector2 = np.random.randint(0, len(vector1), 10)
print(vector1)
print(vector2)
vector1 += np.bincount(vector2, minlength=len(vector1))
print(vector1)

[1 1 1 1 1 1 1 1 1 1]
[9 0 4 5 8 3 2 1 7 4]
[2 2 2 2 3 2 1 2 2 2]


In [24]:
np.add.at(vector2, vector1, 1)
print(vector1)

[1 3 1 3 2 2 1 2 3 2]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [11]:
X = np.arange(8)
I = [1,1,5,8,9,10,10,9]
F = np.bincount(I,X)
print(F)

[ 0.  1.  0.  0.  0.  2.  0.  0.  3. 11. 11.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [26]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2]
print(len(np.unique(F)))

8
