# Chapter 2 . 사이킷런으로 시작하는 머신러닝

## 01. 사이킷런 소개와 특징
- 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향한만큼 쉽고 파이썬스러운 API 제공
- 머신러닝을 위한 매우 다양한 알고리즘, 개발을 위한 편리한 프레임워크/API 제공
- 오랜 기간 실전 환경에서 검증, 매우 많은 환경에서 사용됨

## 02. 첫번째 머신러닝 만들어보기 - 붓꽃 품종 예측하기
- 붓꽃의 품종 분류 
- 분류 : 대표적 지도학습 (학습을 위한 다양한 피처와 레이블 데이터로 모델을 학습 후 별도의 테스트 데이터 세트에서 미지의 레이블 예측)
 - 사이킷런 패키지 내 모듈명 sklearn으로 시작 
 - sklearn.model_selection : 학습 데이터 / 검증 데이터 / 예측데이터로 분리 OR 최적의 하이퍼파라미터로 평가하기 위한 모듈 모임
 - 하이퍼 파라미터 : 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터 통칭. 머신러닝 알고리즘 성능 튜닝 가능

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


# 데이터 세트 준비
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_label = iris.target

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

# 의사결정 트리를 이요한 학습과 예측 수행
# 1) 학습용 데이터 / 테스트용 데이터 세트 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

# 의사결정 트리 클래스 객체로 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 2) 모델 학습 
dt_clf.fit(X_train,y_train)

# 3) 예측 수행
# 테스트 데이터 세트로 수행, 학습데이터 사용하면 안됨
pred = dt_clf.predict(X_test)

# 4) 예측 성능 평가 - 정확도
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9333333333333333

## 03. 사이킷런의 기반 프레임워크 익히기

### (1) Estimator 이해 및 fit(), predict() 메서드  
#### a) 지도학습 (분류, 회귀)
- fit() : 모델 학습
- predict() : 학습된 모델의 예측
- estimator : 지도학습의 모든 알고리즘을 구현한 클래스 통칭 (Classifier / Regressor). 파라미터 튜닝을 지원하는 클래스 및 evaluation 함수의 인자로 사용

#### b) 비지도학습
- 차원축소, 클러스터링, 피처 추출
- fit() : 입력형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
- transform() : 사전 구조를 맞춘 이후 입력 데이터의 차원 변환, 클러스터링, 피처 추출 등의 실제 작업 수행
- fit_transform()을 통해 한번에 사용 가능

### (2) 사이킷런의 주요 모듈
- sklearn.datasets
- sklearn.preprocessing, sklearn.feature_selection
- sklearn.feature_extraction : 피처 처리 (추출)
- sklearn.decomposition : 차원 축소
- sklearn.model_selection : 교차검증위한 분리, 그리드 서치로 최적 파라미터 추출
- sklearn.metrics : 분류, 회귀, 클러스터링, 페어와이즈에 대한 성능측정 (정확도, RMSE 등)
- ML 알고리즘 모듈 : sklearn.ensemble, sklearn.linear_model, sklearn.naive_bayes, sklearn.neighbors, sklearn.svm, sklearn.tree, sklearn.cluster
- sklearn.pipeline

### (3) 내장된 예제 데이터 세트
- 분류, 회귀 연습용 예제 데이터
 - datasets.load_boston(), datasets.load_breast_cancer(), datasets.load_diabetes(), datasets.load_digits(), datasets.load_iris()
 - 일반적으로 딕셔너리 형태
 - 키 : data(ndarray), target(ndarray), target_name(list or ndarray), feature_names(list or ndarray)/DESCR(str)
- fetch 계열 명령 데이터 (최초 사용시 인터넷에 연결)
 - fetch_covtype(), fetch_20newsgroups(), fetch_olivetti_faces(), fetch_lfw_people(), fetch_lfw_pairs(), fetch_rcv1, fetch_mldata()
- 분류, 클러스터링 용 표본데이터 생성기
 - datasets.make_classifications(), datasets.make_blobs()

In [16]:
from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))
print(iris_data.keys())

# 객체 키 출력
print('\n feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data.data[0:3])

print('\n target의 type:', type(iris_data.target))
print('target의 shape:', iris_data.target.shape)
print(iris_data.target[0:3])

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

 feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

 target의 type: <class 'numpy.ndarray'>
target의 shape: (150,)
[0 0 0]


## 04. Model Selection 모듈 소개

### (1) 학습/테스트 데이터 세트 분리 - train_test_split()
- test_size : 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할 것인가
- train_size : 전체 데이터에서 학습용 데이터 세트 크기를 얼마로 샘플링할 것인가
- shuffle : 데이터를 분리하기 전 데이터를 미리 섞을지 결정 (default=True)
- random_state
- 튜플 형태로 반환

In [19]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label,pred))
# 이미 학습한 데이터 세트를 기반으로 예측시 예측 정확도가 100%가 됨

예측 정확도: 1.0


- 테스트 데이터 세트를 전체의 30%, 학습 데이터 세트를 70%로 분리

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

# 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

# 학습 데이터 학습 수행 후 모델의 정확도 측정
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도:', accuracy_score(y_test, pred))

예측 정확도: 0.9555555555555556


### (2) 교차 검증
- 모델이 학습데이터에만 과도하게 최적화되는 과적합 발생 위험
- 성능 평가시 테스트 데이터에만 최적의 성능을 발휘하도록 편향되게 모델을 유도할 위험
- 교차검증의 필요성 
 - 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행
 - 각 세트에서 수행한 평가 결과에 따라 하이퍼 파라미터 튜닝 등의 모델 최적화 손쉽게 진행
 
#### a) K 폴드 교차 검증
- K개의 데이터 폴드 세트를 만들어 각 폴드 세트에 학습과 검증 평가 반복적으로 수행
- 학습 데이터 세트와 검증 데이터 세트를 점진적으로 변경하면서 마지막 K번째까지 학습과 검증 수행


In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [9]:
n_iter = 0
# KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index, in kfold.split(features):
    # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도:{1}, 학습데이터 크기: {2}, 검증데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)


#1 교차 검증 정확도:1.0, 학습데이터 크기: 120, 검증데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도:0.9667, 학습데이터 크기: 120, 검증데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도:0.8667, 학습데이터 크기: 120, 검증데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도:0.9333, 학습데이터 크기: 120, 검증데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도:0.7333, 학습데이터 크기: 120, 검증데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


#### b) Stratified K 폴드
- 불균형한 데이터 분포도를 가진 레이블 데이터 집합을 위한 K 폴드 방식

In [10]:
import pandas as pd

iris=load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [11]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index, in kfold.split(iris_df):
    n_iter += 1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n',label_train.value_counts())
    print('검증 레이블 데이터 분포:\n',label_test.value_counts())    
# 데이터 불균형하게 분포, 학습 데이터에 있는 레이블만 예측 가능

## 교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [12]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index, in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n',label_train.value_counts())
    print('검증 레이블 데이터 분포:\n',label_test.value_counts())    

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [13]:
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]


# StratifiedKFold의 split 호출시 반드시 레이블 데이터 세트를 추가입력해야함
for train_index, test_index, in skfold.split(features, label):
    # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    # 반복 시마다 정확도 측정
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도:{1}, 학습데이터 크기: {2}, 검증데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    
# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy,4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도:0.98, 학습데이터 크기: 100, 검증데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도:0.94, 학습데이터 크기: 100, 검증데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도:0.98, 학습데이터 크기: 100, 검증데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


#### c) 교차 검증을 보다 간편하게 - cross_val_score()
- 다음과 같은 과정을 한꺼번에 수행해주는 API
 - 폴드 세트 설정
 - for 루프에서 반복적으로 학습 및 테스트데이터의 인덱스 추출
 - 반복적으로 학습과 예측 수행 후 예측 성능을 반환
- cross_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs')
 - scoring : 예측성능평가지표
 - cv : 교차 검증 폴드 수
 - 반환 : 지정된 성능 지표 측정값을 배열 형태로 반환
- classifier가 입력되면 stratified K폴드 방식으로 레이블값 분포에 따라 데이터 세트 분할
 - 회귀인 경우는 K 폴드 방식으로 분할 
 
#### +) cross_validate() 
- cross_val_score과 비슷한 API
- 여러개의 평가 지표 반환
- 학습 데이터에 대한 성능 평가 지표와 수행 시간 또한 제공

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도 (accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print("교차 검증별 정확도:", np.round(scores,4))
print("평균 검증 정확도:", np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


### (3) GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에
- 하이퍼 파라미터 : 머신러닝 알고리즘의 주요 구성 요소, 값을 조정해 ML 성능 개선 가능
- GridSearchCV API 이용해 classifier/regressior 등에 사용되는 하이퍼파라미터 순차적으로 입력하며 최적의 파라미터 도출
- 순차적으로 파라미터를 테스트하므로 수행시간이 상대적으로 오래 걸림

- 주요 파라미터
 - estimator : classifier / regressor / pipeline
 - param_grid : 딕셔너리형. estimator의 튜닝을 위한 파라미터명과 파라미터값 지정
 - scoring : 예측성능 측정 평가방법 지정 (문자열 혹은 함수 지정)
 - cv : 교차 검증을 위해 분할되는 학습/테스트 세트의 개수
 - refit : default=True, True시 최적의 하이퍼파라미터를 찾은 뒤입력된 estimator객체를 해당 하이퍼파라미터로 재학습시킴

In [15]:
grid_parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 1) 데이터를 로딩하고 학습데이터와 테스트데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

# 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}
# decision tree classifier의 중요 하이퍼파라미터

import pandas as pd
# param_grid의 하이퍼파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정, refit=True
grid_dtree = GridSearchCV(dtree,param_grid=parameters,cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GradSearchCV 결과를 추출해 dataframe으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_) # cv_result_ : gridsearchcv의 결과세트
scores_df[['params', 'mean_test_score','rank_test_score','split0_test_score', 'split1_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  
0              0.700                0.7  
1              0.700                0.7  
2              0.925                1.0  
3              0.925                1.0  
4              0.975                1.0  
5              0.975                1.0

In [16]:
print("GridSearchCV 최적 파라미터:", grid_dtree.best_params_)
print("GridSearchCV 최고 정확도: {0:.4f}".format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9750


In [19]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

# 이미 최적의 학습이 되었으므로 별도의 학습은 필요 없고 바로 예측이 가능
pred = estimator.predict(X_test)
print("테스트 데이터 세트 정확도: {0:.4f}".format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


## 05. 데이터 전처리 

- 결손값 (NaN, Null 값) 고정된 다른 값으로 변환
 - 피처의 평균값 등으로 대체, Null 값이 대부분이라면 드롭
- 모든 문자열 값 인코딩해 숫자형으로 변환
 - 카테고리형 피처 : 코드값으로 표현
 - 텍스트형 피처 : 피처 벡터화, 불필요한 피처인 경우 삭제

### (1) 데이터 인코딩
#### a) 레이블 인코딩
- 카테고리 피처를 코드형 숫자 값으로 변환
- 간단하게 문자열 값을 숫자형 카테고리 값으로 변환
- 숫자 크기의 특성이 작용해 알고리즘에 적용할 경우 예측 성능이 떨어지는 경우 발생 가능
 - 선형 회귀와 같은 ML 알고리즘에 적용하지 않아야 함
 - 트리 계열의 ML 알고리즘에는 적용 가능

In [20]:
from sklearn.preprocessing import LabelEncoder
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성 후 fit(), transform()으로 인코딩
encoder = LabelEncoder() 
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값:", labels)
print("인코딩 클래스:", encoder.classes_) # 고유한 값들만 반환
print("디코딩 원본값:", encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


#### b) 원-핫 인코딩
- 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시
- 사이킷런 OneHotEncoder 클래스 사용
 - 모든 문자열 값이 숫자형 값으로 변환돼야 함
 - 입력값으로 2차원 데이터가 필요

In [22]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 숫자 값으로 변환 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환
labels = labels.reshape(-1,1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print("원-핫 인코딩 데이터")
print(oh_labels.toarray())
print("원-핫 인코딩 데이터 차원")
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [23]:
# 판다스에서의 원-핫 인코딩 : 숫자형으로 변환 없이도 적용 가능
import pandas as pd
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### (2) 피처 스케일링과 정규화
- 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
- 표준화 : 데이터 피처 각각이 평균 0, 분산 1인 가우시안 정규분포 값으로 변환
- 정규화 : 서로 다른 피처의 크기를 통일, 개별 데이터의 크기를 모두 똑같은 단위로 변경
 - 사이킷런 전처리에서의 Normalizer 모듈은 선형대수에서의 정규화 개념을 적용해 개별 벡터의 크기를 맞춤
 
#### a) StandardScaler
- 표준화 지원 클래스
- SVM, 선형 회귀, 로지스틱 회귀 데이터는 가우시안 분포 가정, 사전에 표준화 적용이 예측 성능 향상에 도움

In [24]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)

print("feature 들의 평균 값")
print(iris_df.mean())
print("\nfeature 들의 분산 값")
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [25]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler() 
# StandardScaler로 데이터 세트를 변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) 

# transform()시 ndarray로 반환된 데이터 세트를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print("feature 들의 평균 값")
print(iris_df_scaled.mean())
print("\nfeature 들의 분산 값")
print(iris_df_scaled.var())

# 평균은 0, 분산은 1에 근사

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### b) MinMaxScaler
- 데이터값을 0과 1 사이의 범위값으로 변환 (음수값 존재시 -1에서 1 사이 범위값)
- 가우시안 분포가 아닌 데이터에 적용 가능

In [26]:
from sklearn.preprocessing import MinMaxScaler

# 1) MinMaxScaler 객체 생성
scaler = MinMaxScaler() 

# 2) MinMaxScaler로 데이터 세트를 변환, fit()과 transform()호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) 

# 3) transform()시 ndarray로 반환된 데이터 세트를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
print("feature 들의 최솟값")
print(iris_df_scaled.min())
print("\nfeature 들의 최댓값")
print(iris_df_scaled.max())

feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature 들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### c) 학습 데이터나 테스트 데이터의 스케일링 변환 시 유의점
- Scaler 객체를 이용해 학습 데이터 세트로 fit과 transform을 적용하면 테스트 데이터세트로는 다시 fit()을 수행하지 않고 학습 데이터 세트로 fit()을 수행한 결과를 이용해 transform() 변환을 적용해야 함
- 테스트데이터로 다시 새로운 스케일링 기준 정보를 만들게 되면 올바른 예측/결과도출 불가
 - 서로 다른 원본값이 동일한 값으로 변환되는 결과 초래
 - 반드시 테스트 데이터는 학습 데이터의 스케일링 기준에 따라야 함
- fit_transform()을 적용하는 경우
 - 해당 메소드는 fit()과 transform()을 순차적으로 수행하기 때문에 학습데이터는 상관 없지만 테스트 데이터에서는 절대 사용해서는 안됨
 - 학습과 데이터 세트로 분리하기 전에 전체 데이터 세트에 스케일링을 적용한 뒤 학습과 테스트 ㅅ데이터 센트로 분리하는 것이 바람직함
 - 여의치 않다면 테스트 데이터 변환 시에는 fit()이나 fit_transform()을 적용하지 않고 학습데이터로 이미 fit()된 Scaler 객체를 이용해 transform()으로 변환

In [29]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler의 fit(), transform()은 2차원 이상 데이터만 가능하므로 차원을 변경
train_array = np.arange(0, 11).reshape(-1,1)
test_array = np.arange(0, 6).reshape(-1,1)

# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1값으로 변환
scaler = MinMaxScaler() 

# fit() 하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정됨
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터를 변환하여 원본 10 -> 1로 변환됨
train_scaled = scaler.transform(train_array)

print("원본 train_array 데이터:", np.round(train_array.reshape(-1),2))
print("Scale된 train_array 데이터:", np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [30]:
# 테스트 데이터 세트 변환, fit()을 호출해 스케일링 기준 정보 적용한 뒤 transform()결과

scaler.fit(test_array)
# 1/5 scale로 test_array 데이터를 변환하여 원본 5 -> 1로 변환
test_scaled = scaler.transform(test_array)

print("원본 test_array 데이터:", np.round(test_array.reshape(-1),2))
print("Scale된 test_array 데이터:", np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [31]:
# 학습 데이터로 fit()을 수행한 객체의 transform()을 이용해 테스트 데이터 변환

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print("원본 train_array 데이터:", np.round(train_array.reshape(-1),2))
print("Scale된 train_array 데이터:", np.round(train_scaled.reshape(-1),2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 바로 transform()만으로 변환해야 함
test_scaled = scaler.transform(test_array)
print("\n원본 test_array 데이터:", np.round(test_array.reshape(-1),2))
print("Scale된 test_array 데이터:", np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
